version: "3"

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  install:
    desc: installs pipenv and all packages in the pipfile
    cmds:
      - python -m pip install --upgrade pip
      - python -m pip install --upgrade pipenv
      - pipenv install
  format:
    desc: Auto formats the code and auto fixes smells
    cmds:
      - pipenv run black .
      - pipenv run ruff check . --fix

  lint:
    desc: Verify that all coding standards are followed
    cmds:
      - pipenv run black . --check
      - pipenv run ruff check .

  test:
    desc: Runs the complete test suite
    aliases: [tests]
    cmd: pipenv run pytest .
