version: "3"

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  install:
    desc: installs pipenv and all packages in the pipfile
    cmds:
      - pipenv install -d
  format:
    desc: Auto formats the code and auto fixes smells
    cmds:
      - pipenv run black .
      - pipenv run ruff check . --fix
  unsafe-format:
    desc: Auto formats the code and auto fixes smells (even unsafe)
    cmds:
      - pipenv run black .
      - pipenv run ruff check . --fix --unsafe-fixes

  lint:
    desc: Verify that all coding standards are followed
    cmds:
      - pipenv run black . --check
      - pipenv run ruff check .

  test:
    desc: Runs the complete test suite
    aliases: [tests]
    cmd: pipenv run pytest . -vv
