version: "3"

tasks:
  default:
    aliases: [help]
    desc: Prints help message and list all
    cmds:
      - task -l
    silent: true
  install:
    desc: installs pdm and all packages in the pipfile
    cmds:
      - pdm install -d
  format:
    desc: Auto formats the code and auto fixes smells
    cmds:
      - pdm run black .
      - pdm run ruff check . --fix
  unsafe-format:
    desc: Auto formats the code and auto fixes smells (even unsafe)
    cmds:
      - pdm run black .
      - pdm run ruff check . --fix --unsafe-fixes

  lint:
    desc: Verify that all coding standards are followed
    cmds:
      - pdm run black . --check
      - pdm run ruff check .

  test:
    desc: Runs the complete test suite
    aliases: [tests]
    cmd: pdm run pytest . -vv

  test-coverage:
    desc: Runs the complete test suite
    aliases: [tests]
    cmd: pdm run pytest --cov=src .

  build:
    desc: Builds the pypi package
    cmd: pdm build

  publish:
    desc: Publishes the pypi package
    cmd: pdm publish