name: Quality Assurance

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        cache: true
      - name: Install dependencies
        run: |
          task install
      - name: Check format and smells
        run: |
          task lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        cache: true
      - name: Install dependencies
        run: |
          task install
      - name: Run tests
        run: |
          task test
