name: Verify Code Quality

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Check format and smells
        run: |
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pipenv"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: run tests
        run: |
          pipenv run test
